# Generated by Django 4.2.1 on 2023-06-08 00:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargotype", models.IntegerField(unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CartonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cartontype", models.CharField(max_length=255)),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "orderkey",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Being Formed"),
                            ("collecting", "Being Collected"),
                            ("collected", "Collected"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                (
                    "sku",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("cargotypes", models.ManyToManyField(to="items.cargotype")),
            ],
        ),
        migrations.CreateModel(
            name="OrderSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.order"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.sku"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="skus",
            field=models.ManyToManyField(through="items.OrderSku", to="items.sku"),
        ),
    ]
