# Generated by Django 4.2.1 on 2023-06-18 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargotype",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Карготип"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Карготип",
                "verbose_name_plural": "Карготипы",
                "ordering": ["cargotype"],
            },
        ),
        migrations.CreateModel(
            name="CartonType",
            fields=[
                (
                    "barcode",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Штрихкод",
                    ),
                ),
                (
                    "cartontype",
                    models.CharField(
                        max_length=255, verbose_name="Тип упаковки"
                    ),
                ),
                ("length", models.FloatField(verbose_name="Длина")),
                ("width", models.FloatField(verbose_name="Ширина")),
                ("height", models.FloatField(verbose_name="Высота")),
            ],
            options={
                "verbose_name": "Упаковка",
                "verbose_name_plural": "Упаковки",
                "ordering": ["cartontype"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "barcode",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=4)),
            ],
            options={
                "verbose_name": "Ячейка",
                "verbose_name_plural": "Ячейки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CellOrderSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Ячейка с товарами из заказа",
                "verbose_name_plural": "Ячейки с товарами из заказа",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "orderkey",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID заказа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Being Formed"),
                            ("collecting", "Being Collected"),
                            ("collected", "Collected"),
                        ],
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "whs",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Код сортировочного центра"
                    ),
                ),
                (
                    "total_packages",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество упаковок в заказе",
                    ),
                ),
                (
                    "sel_calc_cube",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Объем выбранной упаковки",
                    ),
                ),
                (
                    "pack_volume",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Рассчитанный объем упакованных товаров",
                    ),
                ),
                (
                    "tracking_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="ID доставки",
                    ),
                ),
                (
                    "goods_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Общий вес товаров"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "recommended_cartontype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_orders",
                        to="items.cartontype",
                        verbose_name="Рекомендуемый тип упаковки",
                    ),
                ),
                (
                    "selected_cartontypes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selected_orders",
                        to="items.cartontype",
                        verbose_name="Выбранные типы упаковки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="Sku",
            fields=[
                (
                    "sku",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("length", models.FloatField(verbose_name="Длина")),
                ("width", models.FloatField(verbose_name="Ширина")),
                ("height", models.FloatField(verbose_name="Высота")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "goods_wght",
                    models.FloatField(default=0.0, verbose_name="Вес товара"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sku_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название товара"
                    ),
                ),
                (
                    "cargotypes",
                    models.ManyToManyField(
                        to="items.cargotype", verbose_name="Карготипы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="OrderSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        verbose_name="Количество товара в заказе"
                    ),
                ),
                (
                    "packaging_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Номер упаковки в которой находится товар",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_skus",
                        to="items.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.sku",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товары в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="skus",
            field=models.ManyToManyField(
                help_text="Выберите товары",
                related_name="orders",
                through="items.OrderSku",
                to="items.sku",
                verbose_name="Товары",
            ),
        ),
    ]
