# Generated by Django 4.2.1 on 2023-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='available',
        ),
        migrations.AlterField(
            model_name='sku',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
