# Generated by Django 4.2.1 on 2023-06-17 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="cargotypes",
            field=models.ManyToManyField(
                to="items.cargotype", verbose_name="Карготипы"
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordersku",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_skus",
                to="items.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="ordersku",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="items.sku",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="recommended_cartontype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_orders",
                to="items.cartontype",
                verbose_name="Рекомендуемый тип упаковки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_cartontypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="selected_orders",
                to="items.cartontype",
                verbose_name="Выбранные типы упаковки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sku",
            field=models.ManyToManyField(
                help_text="Выберите товары",
                related_name="orders",
                through="items.OrderSku",
                to="items.sku",
                verbose_name="Товары",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="who",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="cellordersku",
            name="cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.cell",
            ),
        ),
        migrations.AddField(
            model_name="cellordersku",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.order",
            ),
        ),
        migrations.AddField(
            model_name="cellordersku",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.sku",
            ),
        ),
        migrations.AddField(
            model_name="cell",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.table",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_name_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="cell",
            constraint=models.UniqueConstraint(
                fields=("name", "table"), name="unique_cell_table"
            ),
        ),
    ]
