# Generated by Django 4.2.1 on 2023-06-11 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_sku_available_alter_sku_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersku',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trackingid',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
