# Generated by Django 4.2.1 on 2023-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargotype',
            options={'ordering': ['cargotype'], 'verbose_name': 'Карготип', 'verbose_name_plural': 'Карготипы'},
        ),
        migrations.AlterModelOptions(
            name='cartontype',
            options={'ordering': ['cartontype'], 'verbose_name': 'Упаковка', 'verbose_name_plural': 'Упаковки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['sku'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='box_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
