# Generated by Django 4.2.1 on 2023-06-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="order",
        ),
        migrations.AlterField(
            model_name="cellordersku",
            name="cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.cell",
            ),
        ),
        migrations.AlterField(
            model_name="cellordersku",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.order",
            ),
        ),
        migrations.AlterField(
            model_name="cellordersku",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellorder_skus",
                to="items.sku",
            ),
        ),
    ]
