# Generated by Django 4.2.1 on 2023-06-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_order_box_num_order_pack_volume_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sku",
            old_name="quantity",
            new_name="available_quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="skus",
        ),
        migrations.AddField(
            model_name="ordersku",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ordersku",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderskus",
                to="items.order",
            ),
        ),
    ]
