# Generated by Django 4.2.1 on 2023-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellordersku",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
