# Generated by Django 4.2.1 on 2023-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_cellordersku_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sku",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_name_user"
            ),
        ),
    ]
