# Generated by Django 4.2.1 on 2023-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_cargotype_options_alter_cartontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
