# Generated by Django 4.2.1 on 2023-06-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_ordersku_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
