# Generated by Django 4.2.1 on 2023-06-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_pub_data_order_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sku', to='items.sku'),
        ),
    ]
