# Generated by Django 4.2.1 on 2023-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_sku_description_sku_title_alter_table_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sku",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sku",
            name="title",
        ),
        migrations.AddField(
            model_name="sku",
            name="name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название товара"
            ),
            preserve_default=False,
        ),
    ]
