# Generated by Django 4.2.1 on 2023-06-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['id'], 'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
    ]
