# Generated by Django 4.2.1 on 2023-06-17 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_printer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='printer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.printer', verbose_name='принтер'),
        ),
        migrations.AddField(
            model_name='user',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.table', verbose_name='стол'),
        ),
    ]
